AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a VPC with subnets.

Parameters:
  VpcCidrBlock:
    Type: String
    Description: The CIDR block for the VPC
    Default: 10.0.0.0/16
  PublicSubnetCidrBlock:
    Type: String
    Description: The CIDR block for the public subnet
    Default: 197.0.0.0/18
  PrivateSubnetCidrBlock:
    Type: String
    Description: The CIDR block for the private subnet
    Default: 197.0.64.0/18
  AvailabilityZone:
    Type: String
    Description: The availability zone for the resources

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: name
          Value: PET-APP-VPC
        - Key: env
          Value: learning

  InternetGateway:
    Type: AWS::EC2::InternetGateway
  
  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain : vpc
    
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC

  PrivateRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
        VpcId: !Ref MyVPC
        Tags:
          - Key: name
            Value: pet-public-route-table

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: PublicSecurityGroup
      GroupDescription: Security group for the public subnets
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8789
          ToPort: 8789
          CidrIp: 0.0.0.0/0

  PrivateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: PrivateSecurityGroup
      GroupDescription: Security group for the private subnet
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8789
          ToPort: 8789
          CidrIp: 0.0.0.0/0



Outputs:
  PetVPC:
    Description: The VPC for pet app 
    Value: !GetAtt MyVPC.VpcId
    Export:
      Name: PetVPCID

  PetInternetGateway:
    Description: The internet gateway for this vpc 
    Value: !GetAtt InternetGateway.InternetGatewayId
    Export:
      Name: PetInternetGatewayID

  PrivateSecurityGroupID:
    Description:  Private Security Group ID
    Value: !GetAtt PrivateSecurityGroup.GroupId
    Export:
      Name: PetPrivateSecurityGroup

  PublicSecurityGroupID:
    Description:  Public Security Group ID
    Value: !GetAtt PublicSecurityGroup.GroupId
    Export:
      Name: PetPublicSecurityGroup


  PrivateRouteTableID:
    Description: Private route table  id 
    Value:  !GetAtt PrivateRouteTable.RouteTableId
    Export:
      Name: PrivateRouteTableID  

  PublicRouteTableID:
    Description: Public route table  id 
    Value:  !GetAtt PublicRouteTable.RouteTableId
    Export:
      Name: PublicRouteTableID

  NatEIP:
    Description: NAT Elastic IP  
    Value:  !GetAtt 'NatEIP.AllocationId'
    Export:
      Name: NatEIP